### PR TITLE
added DH_UPGRADE_PIP to Buildsystem

### PR DESCRIPTION
**Pull request by kkvilekval**
Here's a small change to allow DH_UPGRADE_PIP to specified version for buildystem builds

### CODE REVIEW

**Comment by nailor** [comment]
Hi!

Sorry for the late response and thanks for your PR.

Could you add documentation for this feature too?

**Comment by kkvilekval** [comment]
I've added a couple of lines of documentation and separated out the upgrade of setuptools into it's own variable.  maybe overkill.

**Comment by jhermann** [comment]
While you're at it, the 3rd system thing that should be provided / updated is `wheel`.

**Comment by kkvilekval** [comment]
Added DH_UPGRADE_WHEEL to the mix.

**Comment by nailor** [comment]
Thanks for your contribution, consider it merged :)

**Pull request merged**
