### PR TITLE
Add an environment variable to be able to change the virtualenv folder name

### PR DESCRIPTION
**Pull request by joac**
I was needing to put the virtualenv in a hidden folder. Adding an environment variable was the easiest way to do that.

### CODE REVIEW

**Comment by nailor** [comment]
Hi, and thanks for the pull request! It seems to be failing tests, which need fixing.

In addition to that can you provide a rationale why not just write the whole package into a hidden folder? I'm not sure I'm keen on migrating the customisation virtual environment directory into the mainline if this is the only use case.

**Comment by jhermann** [comment]
Also, isn't there the other env var now to set the root installation path – which would include this use case?!

**Comment by nailor** [comment]
Yeah, that's what I meant, i.e. you can set the install root to point to a hidden folder.

It's documented [here](https://dh-virtualenv.readthedocs.org/en/0.9/usage.html#building-packages-with-dh-virtualenv) in the second chapter

**Comment by nailor** [comment]
I'm closing this pull request for now, as the result can be accomplished by using existing mechanisms.

**Pull request closed without merging**
