### PR TITLE
Debian cleanups

### PR DESCRIPTION
**Pull request by ukleinek**
While checking for the state of [debian bug 936392](https://bugs.debian.org/936392) I noticed a few
things in `debian/` that wanted an update. Here are the changes I found.
Note `lintian` still finds the following faults that I didn't address:

    W: dh-virtualenv: embedded-javascript-library usr/share/doc/dh-virtualenv/html/_static/jquery.js please use libjs-jquery
    W: dh-virtualenv: embedded-javascript-library usr/share/doc/dh-virtualenv/html/_static/underscore.js please use libjs-underscore

These come from using spinx, not sure if these should be overwritten.

    I: dh-virtualenv source: testsuite-autopkgtest-missing

Would be nice, but was out-of-scope for my plan to just check what must happen to fix Python3 compatibility :-)

    P: dh-virtualenv source: package-does-not-install-examples doc/examples/

Didn't care to fix.

    P: dh-virtualenv source: package-uses-old-debhelper-compat-version 12

I don't understand this one, AFAIK 12 is still the recommended version.

I hope to make it a bit easier for you to upload a version now that prevents removal of dh-virtualenv from Debian.

### CODE REVIEW

**Comment by nailor** [comment]
And thanks for another stellar PR! 😊

**Comment by ukleinek** [comment]
I did this to suggest that an upload to Debian is due :-) Are you planning to work on that? Is your usual sponsor available? (If not, feel free to ping me.)

**Comment by nailor** [comment]
Good push @ukleinek 😁  I think my sponsor is available, so I've pinged them. Package is now uploaded and I can reach out to you if they are no longer available.

Go get while it is hot 😜 https://mentors.debian.net/package/dh-virtualenv

**Comment by nailor** [comment]
@ukleinek And it's uploaded to unstable, thanks for prodding me 😊

**Pull request merged**
