### PR TITLE
New refactored manual structure with new chapters

### PR DESCRIPTION
**Pull request by jhermann**
I ended up adding a little more than just how-tos… :wink: 

There's still a lot of TODOs, but it sets the stage for a v1.1 manual.

### CODE REVIEW

**Comment by nailor** [comment]
Just wanted to comment quickly that this looks great! Long overdue refresh!

**Comment by jhermann** [comment]
Well, I'm done for now, this can be merged.

**Comment by jhermann** [comment]
Well, now I'm done-done. :clown_face:

**Comment by nailor** [comment]
Looks really great! I had a minor comment on the legal matter with copyright plus not sure what are our internal guidelines for the logo. If we drop the logo from the equation and postpone the copyright change I’ll happily merge this!

**Comment by jhermann** [comment]
The copyright change just reflects reality (according to US law at least), no CLA means individual contributors retain their copyright, and everyone licenses to everyone. But I understand the maze of corporate legal stuff.

Logo is hidden for now, so it can be reviewed.

**Comment by nailor** [comment]
Yeah, you are probably right about the copyright! I’ll aim to clear it when back at work (also ping @econchick as she probably knows better than me about this)

Will merge this

**Comment by jhermann** [comment]
@nailor #240 fixes the CSS I broke in production, BTW ;)

**Pull request merged**
