### PR TITLE
Switch install location to /opt

### LINKED ISSUE #82: Consider changing install location
Currently `dh-virtualenv` installs packages into `/usr/share/python/$packagename`. As far as I understand `/usr/share/python` is for system python packages only and other packages should be installed somewhere else (`/usr/share/$packagename` maybe?).

Installing into `/usr/share/python` may break system python packages.

##### For example, I have run into this issue:
I have a `dh-virtualenv` based package that includes `gunicorn`. When it is installed, `python-minimal` package cannot be upgraded or reinstalled: 
```
Setting up python-minimal (2.7.3-0ubuntu2.2) ...
dpkg: error processing python-minimal (--configure):
 subprocess installed post-installation script returned error exit status 1
```
The reason is this line in `python-minimal.postinst script`:
```
python2.7 -m compileall /usr/share/python/ >/dev/null
```
Which fails with this:
```
[...]
Compiling /usr/share/python/<my-package-name>/lib/python2.7/site-packages/gunicorn/workers/_gaiohttp.py ...
SyntaxError: ('invalid syntax', ('/usr/share/python/<my-package-name>/lib/python2.7/site-packages/gunicorn/workers/_gaiohttp.py', 68, 26, '                yield from self.wsgi.close()\n'))
[...]
```
To upgrade `python-minimal` package I need to remove my package first and then reinstall it after. Which is neither obvious nor convenient.

### PR DESCRIPTION
**Pull request by moritz**
Fixes #82

### CODE REVIEW

**Comment by nailor** [comment]
Hello there!

The change looks good in general, however a few things I'd like to see:

- A changelog entry :)
- A big fat warning somewhere that the behaviour has changed. Maybe not in the README, but in the docs. This is because we are possibly breaking people's builds here

**Comment by moritz** [comment]
Hi @nailor,

I've added a changelog entry to info.rst; where else should the warning go?
Also I assumed this will be 1.0 (since it's a backwards incompatible change from 0.9) -- not sure if that's your intention.

**Comment by nailor** [comment]
Great! 

No, I'm probably not rolling out 1.0 yet, next one will be 0.10. 

One change that escaped me: can you replace the /opt stuff here too: https://github.com/spotify/dh-virtualenv/blob/master/lib/Debian/Debhelper/Buildsystem/dh_virtualenv.pm

**Comment by nailor** [comment]
One of my colleagues made a good point here too: Installing under `/opt` might be bad if people have `/opt/*/bin` in their `PATH` which is not that uncommon. Should we add an additional layer into the path?

**Comment by moritz** [comment]
You mean `/opt/python/` as the install location? Would work for me. (Though anybody who put wildcards into their PATH shouldn't be too surprised if they get a few more paths then they originally wanted).

Also, the premium solution would be to make the installation prefix configurable, though that's probably much more effort.

**Comment by nailor** [comment]
Yeah, something along those lines. Install prefix is actually configurable (see the first chapter here https://dh-virtualenv.readthedocs.org/en/latest/usage.html)

**Comment by nailor** [comment]
Btw, defining `/opt/python` might also be tricky at least for the reasons that if Debian views `/opt/python` directory to be provided by multiple packages, it might just refuse to install (not 100% about this, would need to test / look into docs).

Another option could be installing to `/opt/<packagename>/virtualenv` or `/opt/$packagename/python` or something like this to avoid accidentally providing binaries in `/opt/*/bin`. This could be further improved by automatically detecting the scripts of the installed package (i.e. those defined in `setup.py`, not those scripts installed by other packages) that could then be dropped into `/opt/<packagename>/bin`. 

And yeah, people who put `*` in their `PATH` ask for trouble, but it is unfortunately common when it comes to the `/opt`

**Comment by nailor** [comment]
Since the transition to the new default install location would be hard for existing users and the actual benefits are pretty small, I'm closing this pull request

**Pull request closed without merging**
