### PR TITLE
Building the package in a Docker container

### PR DESCRIPTION
**Pull request by jhermann**

### CODE REVIEW

**Comment by nailor** [comment]
Looks like some intermittent error crashed the build for unknown reasons. 

The addition looks really amazing and probably helps a ton of users, really nice initiative!

Btw, I wonder if this build could be tied in travis (can be done at a later point), as it could give us nice two-fold benefit: 1) verify we can build the package itself and 2) verify that the Dockerfile provided to users as an example still works.

**Comment by nailor** [comment]
(hit restart for that failing build)

**Comment by jhermann** [comment]
Not sure whether Travis offers docker-as-a-service, anyway, later indeed.
This is done and can be merged.

I have the USING side already working (use v1.1 from sid to build your own project), expect another PR for the docs when I come around to refining it.

**Comment by nailor** [comment]
👍 

Merged and thanks once more for the PR 😊

**Comment by jhermann** [comment]
Preview for improved "dpkg-buildpackage in docker" @ https://github.com/1and1/debianized-jupyterhub/blob/master/Dockerfile.build

**Pull request merged**
