### PR TITLE
Escape shebang lines with `re.escape` before passing to sed

### LINKED ISSUE #139: fix_shebangs doesn't work for paths containing hyphens
PR #136 uses a '-' as a delimiter for the sed replace command, which causes errors when fix_shebangs gets a path that contains a hyphen.

Here's an example of it breaking:

```
16:29:14 running test
16:29:14 sed: -e expression #1, char 79: unknown option to `s'
16:29:14 Traceback (most recent call last):
16:29:14   File "/usr/bin/dh_virtualenv", line 106, in <module>
16:29:14     sys.exit(main() or 0)
16:29:14   File "/usr/bin/dh_virtualenv", line 98, in main
16:29:14     deploy.fix_shebangs()
16:29:14   File "/usr/lib/python2.7/dist-packages/dh_virtualenv/deployment.py", line 177, in fix_shebangs
16:29:14     subprocess.check_call(['sed', '-i', regex, f])
16:29:14   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
16:29:14     raise CalledProcessError(retcode, cmd)
16:29:14 subprocess.CalledProcessError: Command '['sed', '-i', 's-^#!.*bin/\\(env \\)\\?\\(python\\|pypy\\|ipy\\|jython\\)-#!/usr/share/python/paasta-tools/bin/python-', 'debian/paasta-tools/usr/share/python/paasta-tools/bin/easy_install']' returned non-zero exit status 1
```

Link to the sed [here](https://github.com/spotify/dh-virtualenv/pull/136/files#diff-b432c676336e8409fc43c7cfdc7c78e1R175)

### PR DESCRIPTION
**Pull request by mjksmith**
Fixes #139 

I chose to change the delimiter to a colon since @jhermann pointed out it's less likely to conflict.

### CODE REVIEW

**Comment by nailor** [comment]
Thanks for the PR!

I wonder how much sense would it to instead of doing this properly and escape the `-` or `:`

**Comment by mjksmith** [comment]
@nailor AFAICT that would pretty simply be `str.replace('-', '\-')`, though maybe you can think of some edge case I can't.

**Comment by nailor** [comment]
Yeah, I don't think it would be any harder than that. Probably worth adding tests for paths that contain `\` or `\-` already, but _should_ be safe :stuck_out_tongue:

**Comment by jhermann** [comment]
BTW, if you're really paranoid (and aren't we all from experience :grin: ), `re.escape`.

**Comment by mjksmith** [comment]
I updated this code to use `re.escape` and added a test that checks `fix_shebangs` against a directory with special chars in it. This test fails without using `re.escape`.

**Comment by nailor** [comment]
Hey, can you reword the PR a bit, since that'll show up in the merged git history?

**Comment by nailor** [comment]
Btw, thanks @jhermann for suggesting the re-escape!

**Comment by nailor** [comment]
I renamed the PR a bit and merged. Thanks!

**Pull request merged**
