### PR TITLE
Add new option --use-tmp-builddir

### PR DESCRIPTION
**Pull request by vnaydionov**
To address issues spotify/dh-virtualenv#10, spotify/dh-virtualenv#97

### CODE REVIEW

**Comment by nailor** [comment]
How is this different from using the `--tmpdir` flag for [debhelper](http://manpages.ubuntu.com/manpages/zesty/man7/debhelper.7.html)?

I'm also bit confused about the correct behaviour when python executable is not in the package (the second commit). When would this happen?

**Comment by vnaydionov** [comment]
> How is this different from using the --tmpdir flag for debhelper?
Sorry, I did not find how I can use this flag in combination with `dh_virtualenv` to achieve the same effect: i.e. create a temporary directory and have `dh_virtualenv` use the directory to create a virtualenv plus install the requiremtns plus clean up.

> I'm also bit confused about the correct behaviour when python executable is not in the package (the second commit). When would this happen?
Just rolled this code back - it won't fully work without tweaking on `postinst` and adding corresponding `postrm` script. This code messed in from my experiments with building of arch-independent packages -- I used to wipe out all of the `*.pyc` and the python interpreter itself after having everything installed.

**Comment by nailor** [comment]
Ah, now I see the issue.

I wonder why I have decided to default until the `debian/`. Maybe we could respect the debhelper's build directory instead (thus avoiding adding a custom, competing flag)?

**Comment by phillipod** [comment]
+1 to respecting debhelpers build directory

**Pull request closed without merging**
