### PR TITLE
(WIP) add a helper script to generate Debian boilerplate

### PR DESCRIPTION
**Pull request by ulzha**

### CODE REVIEW

**Comment by jhermann** [comment]
This seems incomplete – which might or might not be the cause for the missing patch of setuptools.setup (you cannot just patch distutils alone, esp. since the official place is setuptools nowadays).

**Comment by ulzha** [comment]
setuptools.setup is distutils.core.setup: https://bitbucket.org/pypa/setuptools/src/a536ca310dbcb01f3a8e6647c5598e3f99506c10/setuptools/__init__.py?at=default&fileviewer=file-view-default#__init__.py-117

This is work in progress, sorry for forgetting to mark it in the PR title; comments welcome on any problems you find with the approach.

**Comment by jhermann** [comment]
Yes they are the same… until you only patch *one* of them. Names (bindings) and the objects they refer to are not the same in Python.

**Comment by ulzha** [comment]
I'm `execfile`ing setup.py after patching, so anything imported and used in setup.py will get it patched. I did try this with a setup.py file that uses `from setuptools import setup`.

**Comment by jooon** [comment]
Rename it to dh-make-virtualenv

There is a convention already that calls these things dh-make-SOMETHING. https://packages.debian.org/search?keywords=dh-make

**Comment by nailor** [comment]
I'm closing this for now, since it is not completed. Feel free to open if the WIP status ever changes!

**Pull request closed without merging**
