### PR TITLE
buildsystem: allows to specify a virtualenv name

### PR DESCRIPTION
**Pull request by dzen**
The dh_virtualenv target allows to specify a virtualenv name.
this commits introduce a `DH_VIRTUALENV_NAME` vars.

### CODE REVIEW

**Comment by nailor** [comment]
Hi, and thanks for your PR!

This same functionality is called "install suffix" on the 'regular' side of the dh-virtualenv. Just to align the terminology, could you call this the same?

**Comment by dzen** [comment]
I added some doc, and rebased onto master. It added aditionnal commits :cry:

**Comment by nailor** [comment]
Thanks for the changes made! If you could just squash these three together I'm happy to merge!

**Comment by einarf** [comment]
@nailor You can enable commit squashing on all pull requests merged via the merge button now

**Comment by dzen** [comment]
Just updated the branch with squashed commits

**Comment by dzen** [comment]
dont merge this, I just found a bug: the sheebang is wrong for all script installed in `$VIRTUALENV/bin`.

Let me investigate

**Comment by dzen** [comment]
Ok found, we need to change the sheebang rewrite here : https://github.com/Polyconseil/dh-virtualenv/blob/master/lib/Debian/Debhelper/Buildsystem/dh_virtualenv.pm#L152

**Comment by nailor** [comment]
Thanks for your PR!

**Pull request merged**
