### PR TITLE
add cmd option to force upgrade setuptools

### PR DESCRIPTION
**Pull request by honnix**
Add a command line option to force upgrading setuptools to the latest available version in the virtualenv. It seems to be possible using `--buildsystem=dh_virtualenv` but the doc says experimental.

### CODE REVIEW

**Comment by honnix** [comment]
Also I'm a bit confused. What's the difference between this repo and our internal one?

**Comment by jhermann** [comment]
Just use `--preinstall` with a fitting lower version limit.

**Comment by honnix** [comment]
Indeed, so something like `dh $@ --with python-virtualenv --preinstall setuptools>=40.6` ?

**Comment by honnix** [comment]
Minor fix, it should be `dh $@ --with python-virtualenv --preinstall "setuptools>=40.6"`. And I'm closing this PR.

**Comment by honnix** [comment]
Thanks for the help @jhermann !

**Comment by jhermann** [comment]
For clarification & docs, pip upgrade must be special because it is a bootstrap situation. Everything else can then be updated "normal" using the current pip version.

**Pull request closed without merging**
