### PR TITLE
Fix the *.egg-link files

### LINKED ISSUE #200: Packages installed with -e are badly installed
At Ideascube, we use dh-virtualenv to build our Debian package.

Some of our dependencies are specified in our `requirements.txt` file with e.g:

```
-e git+https://github.com/ideascube/django-select-multiple-field@remove-dj110-warning#egg=django-select-multiple-field
```

We just built a package, and it contains the file:

```
$ cat /opt/venvs/ideascube/lib/python3.4/site-packages/django-select-multiple-field.egg-link
/build/ideascube-Ls3MlA/ideascube-0.21.1/debian/ideascube/opt/venvs/ideascube/src/django-select-multiple-field
```

That's clearly the wrong path!

Of course, it's kind of obvious that this is the path which ends up in the `.egg-link` file, since that's the install root passed to pip.

However, dh-virtualenv should probably make a pass on all the `*.egg-link` files at the end of the build process and fix the paths.

### PR DESCRIPTION
**Pull request by bochecha**
I'm not entirely sure how to properly test this, so please review carefully. :)

However, as far as I can see from reading the rest of the dh-virtualenv code, this would fix #200

### CODE REVIEW

**Comment by bochecha** [comment]
Hi, it's been a month, anything I can do? 😃

**Comment by nailor** [comment]
Thanks for your PR and sorry for not getting back!

Could you add some simple tests for this functionality? I.e. take an actual(ish) `egg-link` file and create a test that modifies it

**Comment by bochecha** [comment]
> Could you add some simple tests for this functionality?

I sure can!

The reason I didn't do it right away is that I wasn't sure this was something you'd accept, and I had no idea whether I had hooked the code in the right place. So I figured I'd send a quick pull request as a straw man to get the discussion started.

I've just pushed a new version of this branch with an added test, and I'm glad I did, because there were 3 mistakes in my code:

* there was a silly typo
* I wasn't truncating the file after overwriting it
* I wasn't handling the case where the install prefix is not found in the egg-link file

Those are fixed now.

I'm happy to write more tests for this if you think it's necessary, but first I'd like some reassurance that the idea behind this code is sane. 😄

**Comment by bochecha** [comment]
Also, I'm not entirely sure how to test this in real conditions, that is with an actual Debian package build.

I don't have a Debian machine handy, except for the server where we build our release packages, and I'd rather not test there. 😉

**Comment by nailor** [comment]
Sorry for late reply and thanks for the added tests!

Do you think you could find a real life egg file that could used for testing? I.e. copy that into a temporary location when test starts, modify it and verify results.

And you said you fixed the case where the path didn't exist. Just to avoid regression, can you add a test for that case too?

**Pull request closed without merging**
