### PR TITLE
requirements.txt added #254

### PR DESCRIPTION
**Pull request by sarvesha-jaiswal**
Added " how to use pipenv's conversion feature in the rules file to get a requirements.txt ".

### CODE REVIEW

**Comment by nailor** [comment]
Hi,

Thank you for the pull request. Could you maybe provide some context why addition of this piece of documentation is needed?

**Comment by sarvesha-jaiswal** [comment]
yes sure

**Comment by nailor** [comment]
Hi, 

maybe I phrased my question badly: I’m wondering why we would need to document creation of requests.txt in dh-virtualenv. I’m prone to think documenting that is beyond the scope of this project, and would just add additional burden to maintain if and when creation or format of the file changes. 

The documentation in pull request is good, but I don’t think this is the home for that documentation.

**Comment by nailor** [comment]
Oh and additionally I think some if not all parts of the change are copied from pip’s documentation. Mixing contributions from other projects without prior consent, especially as the licenses differ quite heavily, is not really advised.

I recommend wording these pieces of documentation yourself in the future if there is a need, or even better, provide a link to the correct documentation

**Comment by sarvesha-jaiswal** [comment]
yeah, sure

**Pull request closed without merging**
