### PR TITLE
Support new style pip shebang

### PR DESCRIPTION
**Pull request by nailor**

### CODE REVIEW

**Comment by simmel** [comment]
Hehe, my PR was going to be a bit simpler. Just add `'sh'` to `PYTHON_INTERPRETERS` but this works too = )

Have a great weekend!

**Comment by simmel** [comment]
This PR can be closed since a fixes has been merged in master?

**Comment by nailor** [comment]
Yup, closing

**Comment by nailor** [comment]
Actually, this was never merged in, my bad.

**Pull request merged**
