### PR TITLE
buildsystem: replace sheebang on custom venv installation

### PR DESCRIPTION
**Pull request by dzen**
Hi,

I'm very sorry, and I should have warned you about my perl skills :(

### CODE REVIEW

**Comment by dzen** [comment]
Is there a way to have some unittest on the perl buildsystem ?

**Comment by nailor** [comment]
It would be really nice to have some tests on this stuff, my perl is not top notch either. I've been toying around with an idea to have an integration test builds to actually build debian packages and then inspect them, but haven't gotten around building those.

Thanks for your PR!

**Comment by jhermann** [comment]
@nailor "integration test builds to actually build debian packages and then inspect them"…

https://github.com/Springerle/dh-virtualenv-mold/blob/master/test.sh

**Comment by mgagne** [comment]
This change introduced a regression. See #185

**Pull request merged**
